spring:
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
     registerWithEureka: true
     fetchRegistry: true
management:
  endpoints:
    web:
      exposure:
        include: "*"